// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmecviefmnhttigzamre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZWN2aWVmbW5odHRpZ3phbXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTMxODcsImV4cCI6MjA1NTM4OTE4N30.8LRwp__RbzfsTFOjzhYNoZmQ-vnG0is7MlCRBXL8nVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a simple client with minimal configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);